<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
		<PackageReference Include="IL.FluentValidation.Extensions.Options" Version="11.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.22" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.22" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.22">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="..\.dockerignore">
	    <Link>.dockerignore</Link>
	  </Content>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Playwright.Training.Domain\Playwright.Training.Domain.csproj" />
	  <ProjectReference Include="..\Playwright.Training.Infrastructure\Playwright.Training.Infrastructure.csproj" />
	</ItemGroup>

</Project>
